#server
server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpaPost?serverTimezone=UTC&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  #jpa
  jpa:
    hibernate:
      ddl-auto: create

    #jpa format
    properties:
      hibernate:
        format_sql: true

    show-sql: true



  #log
  output:
    ansi:
      enabled: always